steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/daedongyeomap/backend", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/daedongyeomap/backend"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "daedongyeomap",
        "--image",
        "gcr.io/daedongyeomap/backend",
        "--region",
        "asia-northeast3",
        "--platform",
        "managed",
      ]
images:
  - gcr.io/daedongyeomap/backend
# steps:
#   # Build the container image
#   - name: "gcr.io/cloud-builders/docker"
#     args: ["build", "-t", "gcr.io/$PROJECT_ID/daedongyeomap:$COMMIT_SHA", "."]
#   # Push the container image to Container Registry
#   - name: "gcr.io/cloud-builders/docker"
#     args: ["push", "gcr.io/$PROJECT_ID/daedongyeomap:$COMMIT_SHA"]
#   # Deploy container image to Cloud Run
#   - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
#     entrypoint: gcloud
#     args:
#       - "run"
#       - "deploy"
#       - "daedongyeomap"
#       - "--image"
#       - "gcr.io/$PROJECT_ID/daedongyeomap:$COMMIT_SHA"
#       - "--region"
#       - "asia-northeast3"
#       - "--platform"
#       - "managed"
# images:
#   - "gcr.io/$PROJECT_ID/daedongyeomap:$COMMIT_SHA"
